dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
dotenv: .env
networks:
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
